steps:
  - name: node:12
    id: "Install Dependencies"
    entrypoint: npm
    args: ['install']

  - name: node:12
    id: "Build Gatsby Project"
    entrypoint: npm
    args: ['run', 'build']

  - name: gcr.io/$PROJECT_ID/firebase
    id: "Deploy to Firebase"
    args: ['deploy', "--project=$FIRE_BASE_PROJECT", '--only=hosting']
