backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/media/"
public_folder: "media"

collections:
  - name: "metadata"
    label: "Site Metadata"
    folder: "content/metadata"
    create: true
    fields:
      - {label: "Site Title", name: "siteTitle", widget: "string", default: "Jregistr"}
      - {label: "Coming Soon Message", name: "soonMsg", widget: "string", default: "Coming Soon"}
      - {label: "Repository URL", name: "repoUrl", widget: "string", default: "...."}
      - {label: "Coming Soon Splash", name: "soonSplashImg", widget: "image"}
